// 매번 다른 요청

import static net.grinder.script.Grinder.grinder
import static org.junit.Assert.*
import static org.hamcrest.Matchers.*
import net.grinder.script.GTest
import net.grinder.script.Grinder
import net.grinder.scriptengine.groovy.junit.GrinderRunner
import net.grinder.scriptengine.groovy.junit.annotation.BeforeProcess
import net.grinder.scriptengine.groovy.junit.annotation.BeforeThread
// import static net.grinder.util.GrinderUtils.* // You can use this if you're using nGrinder after 3.2.3
import org.junit.Before
import org.junit.BeforeClass
import org.junit.Test
import org.junit.runner.RunWith


import org.ngrinder.http.HTTPRequest
import org.ngrinder.http.HTTPRequestControl
import org.ngrinder.http.HTTPResponse
import org.ngrinder.http.cookie.Cookie
import org.ngrinder.http.cookie.CookieManager

import org.json.JSONObject;


/**
* A simple example using the HTTP plugin that shows the retrieval of a single page via HTTP.
*
* This script is automatically generated by ngrinder.
*
* @author admin
*/
@RunWith(GrinderRunner)
class TestRunner {

	public static GTest test
	public static HTTPRequest request
	public static Map<String, String> headers = [:]
	public static List<Cookie> cookies = []
	
	public static String imageFileUrl = "http://k.kakaocdn.net"
	public static String name = "최준성"
	public static int age = 25
	public static String sex = "M"
	public static Long zoneId = 1L
	public static Long[] categoryIdList = [1,2,3]
	public static String fcmToken = "123"

	@BeforeProcess
	public static void beforeProcess() {
		HTTPRequestControl.setConnectionTimeout(300000)
		test = new GTest(1, "gjgs-test.com")
		request = new HTTPRequest()

		// Set header data
		headers.put("Content-Type", "application/json")
		grinder.logger.info("before process.")
	}

	@BeforeThread
	public void beforeThread() {
		test.record(this, "test")
		grinder.statistics.delayReports = true
		grinder.logger.info("before thread.")
	}

	@Before
	public void before() {
		request.setHeaders(headers)
		CookieManager.addCookies(cookies)
	
		grinder.logger.info("before. init headers and cookies")
	}

	@Test
	public void test() {
		Long min = 1000000000L
		Long max = 99999999999L
		Long phone = ((Math.random() * (max - min)) + min);
		
		min = 10L
		max = 9223372036854775800L
		Long nickname = ((Math.random() * (max - min)) + min)
		
		Long id = ((Math.random() * (max - min)) + min)
		
		JSONObject testJson= new JSONObject()
		testJson.put("id",id)
		testJson.put("imageFileUrl",imageFileUrl)
		testJson.put("name",name)
		testJson.put("phone",phone)
		testJson.put("nickname",nickname)
		testJson.put("age",age)
		testJson.put("sex",sex)
		testJson.put("zoneId",zoneId)
		testJson.put("categoryIdList",categoryIdList)
		testJson.put("fcmToken",fcmToken)
		String jsonDataStr = testJson.toString()
		
		HTTPResponse response = request.POST("https://gjgs-test.com/api/v1/login/first", jsonDataStr.getBytes())
		if (response.statusCode == 301 || response.statusCode == 302) {
			grinder.logger.warn("Warning. The response may not be correct. The response code was {}.", response.statusCode)
		} else {
			assertThat(response.statusCode, is(200))
		}
	}
}
