# TLauncher configuration file
# Version 
#Sat Jul 11 17:45:37 KST 2026
UPDATER_LAUNCHER=false
chooser.type.account=true
client=bc1f1b09-5f5d-4064-88a9-0a09444e51a9
connection=good
custom.version.warning.show=true
fixed.gpu.jre.error=true
free.partition.size=5
gpu.info=Intel(R) HD Graphics Family
gpu.info.full=\ Intel(R) HD Graphics Family, Intel(R) HD Graphics Family, 2160 MB
gui.console=none
gui.console.height=695
gui.console.width=1295
gui.console.x=45
gui.console.y=87
gui.discord.checkbox=false
gui.frame.fullscreen=false
gui.frame.height=697
gui.frame.width=1072
gui.notice.ad_other=true
gui.notice.ad_server=true
gui.notice.ad_youtube=true
gui.settings.guard.checkbox=true
gui.settings.servers.recommendation=true
gui.statistics.checkbox=false
gui.window=0
locale=en_US
locale1=en
login.version.game=Forge 1.20.1
max.size.for.world=2000
max.time.for.backups=10
minecraft.fullscreen=false
minecraft.gamedir=C\:\\Users\\john\\AppData\\Roaming\\.minecraft
minecraft.java.selected=0
minecraft.language=true
minecraft.memory.ram2=4096
minecraft.memory.ram3=5063
minecraft.onlaunch=hide
minecraft.size=925;530
minecraft.versions.modified=true
minecraft.versions.old_alpha=false
minecraft.versions.old_beta=false
minecraft.versions.release=true
minecraft.versions.snapshot=false
minecraft.versions.sub.old_release=true
minecraft.versions.sub.remote=true
modpack.combobox.index=2
modpack.combobox.name=NeoForge 1.21.1
operating.system.info=Operating System\: Windows 10 Pro 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
process.info=Active code page\: 437
processor.architecture=AMD64
repeat.backup.hours=1
retest.update=true
scaling.setting=100
sending.tlauncher.unique=1783759522208
settings.tip.close=true
settings.version=3
skin.not.work.notification.hide=true
skin.notification.off=true
skin.notification.off.temp=true
skin.status.checkbox.state=true
skip.user.backup=true
updater.delay=1695453598386
updater.offer.installer.delay1=2023-09-23 16\:19\:58
updater.offer.installer.empty.checkbox.delay1=2024-03-31 11\:56\:17
